apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g51e1r8dv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g51e1r8dv-python 
  name: g51e1r8dv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g51e1r8dv-python 
